/**
 *  MINEFIELD
 *  1. GENERATE 16 RANDOM NUMBER FROM 1 TO 100 (BOMBS)
 *  2. ASK THE USER TO INSERT A NUMBER BETWEEN 1 AND 100, IF THE NUMBER IS ALREADY PRESENT IN THE LIST THE GAME IS OVER, OTHERWISE ASK THE USER ANOTHER NUMBER
 *  3. THE GAME IS OVER ONCE THE USER INSERT A PROHIBITED NUMBER OR REACHES THE MAX AVAIABLE NUMBER
 *  4. ONCE THE GAME IS OVER, THE SOFTWARE MUST PRINT THE RESULTS, THE NUMBER OF TIMES THE USER INSERTED A CORRECTED NUMBER
 *  5. BONUS: THE SOFTWARE ASKS FOR A DIFFICULTY AT THE START OF THE GAME: 0 => 1 to 100; 1 => 1 to 80; 2 => 1 to 50;
 * 
/**/